### ISSUE TITLE
BatMass for Win

### ISSUE THREAD

**Issue by MartinHubalek** [chhh/batmass#19]
I am trying to install the BatMass on Win10 PC and am still getting "JVM creation failed". My PC has 16GB RAM, 64-bit OS, installed it non-system location and still, it does not work. Any advice on how to install it?
Martin

**Comment by chhh** [comment]
Hi Martin,
Most likely reason - the install can't figure out how to start java.
Maybe you don't have java installed or maybe you have a version which is too new (you might have noticed that Batmass hasn't been updated in quite a while now).
Simplest way to test:
- Start `cmd.exe` (Win+R, type `cmd`, press Enter), a console window will open
- `java -version` - see if that produces any output, if it does, please post here.

In any case I'd recommend using a `Java 8` build from AdoptOpenJDK or Zulu. Here's a link to Adopt with the right version pre-selected:
https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot

In some cases this still doesn't work, I don't know why, there could be a million reasons particular to your system. But read on.

It's also OK if you don't want to "install" an older version of java, maybe it interferes with the newer one that you might be using. It's easy to download just a zip package of JRE and tell batmass to use it/

Download `Java 8` `JRE` `.zip` package, `x64 version` for your OS from this page:
https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot
Unzip somewhere. In my case I just now downloaded it and unpacked to:
`C:\Users\chhh\Downloads\java\jdk8u292-b10-jre`
![image](https://user-images.githubusercontent.com/107902/121226041-f93d3e00-c83e-11eb-8f99-083e8a836e4e.png)

Now we need to configure batmass to use this particular java binary. Open the following file in text editor:
`<path-to-batmass>\etc\batmass.conf`
Uncomment line 11 (`jdkhome`) and change the path to your unpacked new JRE, in my example: `C:\Users\chhh\Downloads\java\jdk8u292-b10-jre`
![image](https://user-images.githubusercontent.com/107902/121226437-69e45a80-c83f-11eb-91cb-3d2e674dea20.png)
Save the file.
In the same file you will find a line starting with `default_options`, it contains this text `-J-Xmx4G`. This tells Java to use a maximum of 4GB memory. If you want to open very large files, you can increase this number to 8 or 12 maybe on a system with 16GB available.
You can now start batmass either through start menu (if you installed it) or just launch `<path-to-batmass>\bin\batmass64.exe` if you used `batmass.zip` instead of installer.

**Comment by CedricDelporte** [comment]
Hello,
The computing department of my university ask to remove BatMass from my computer for security reason.
I cannot uninstall it because it mentions this: "Cannot load native library from path: native/jnilib/windows/windows-64.dll
![image](https://github.com/chhh/batmass/assets/60658850/e73077c4-8af8-4094-b91a-191213815043)

Could you help me?
Many thanks
Cédric

**Comment by chhh** [comment]
@CedricDelporte Why didn't you open a new issue?

I can't help you much as this software is not being actively maintained. But you can safely just delete the contents of your batmass installation from the hard drive, there isn't anything specific about the "installation". If you don't know where it is installed, you can right click the icon you use to launch it, select Properties and see the location of the executable that is being launched.

I don't really see how batmass can be a security risk though as it doesn't really do anything online. I'm guessing they just scanned it, saw that it includes some old java logging libraries that are "a security risk, because a malicious actor can intercept traffic and execute arbitrary commands". 🤷

**Comment by CedricDelporte** [comment]
@chhh thanks for your reply.
I'll pass it by to the IT team and hope we can keep it because I am quite happy with BatMass :-)
