### ISSUE TITLE
Cannot run Batmass on MacOS X 10.12.5

### ISSUE THREAD

**Issue by lfnothias** [chhh/batmass#8]
Hi,
I wanted to try Batmass, but I could not. 
I installed Batmass (latest release). Installation did not lead to any error. After,  I am not able to open the software in the application folder. Any idea why ?

Thank you,

<img width="418" alt="screen shot 2017-08-04 at 2 48 06 pm" src="https://user-images.githubusercontent.com/22830047/28988282-f0e77b94-7923-11e7-83be-f5c6c0db3700.png">

**Comment by rsalek** [comment]
Could be due to same old problem: The startup shell script script /Applications/batmass.app/Contents/Resources/batmass/bin/batmass is not executable after installation on OSX.
Running "chmod +x .batmass" should fixed the problem.

**Comment by lfnothias** [comment]
Thanks a lot Reza 👍 
To batmass developer, thanks a lot for your tool. I would suggest to keep the issue open for future user, ideally to fix it. It will be problematic for typical MS-software user otherwise.
Thank you

**Comment by chhh** [comment]
@lfnothias There's no such issue on windows. I'm not exactly sure how to fix the issue - the build process with the installers is quite complicated. Theoretically all that should be happening - a file being  copied and renamed. Looks like the permissions on the file are lost somewhere in the process. In past this has happened because of git, because of copy operations, etc. And I don't have a Mac to test it :\ 

Hopefully I'll have access to a Mac soon and will be able to debug it then.
